<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{
    public function findAllWordsInDeck($deck){
        $dql='SELECT w FROM AppBundle:Word w WHERE w.deck = :deck';
        $query=$this->getEntityManager()->createQuery($dql);
        $query->setParameter("deck",$deck);
        return $query->getResult();
    }
}
